name: sequential
version: '0.1.0.0'
category: Distributed Systems
author: David Barsky
maintainer: me@davidbarsky.com
copyright: 2017 David Barsky
license: MIT
github: davidbarsky/sequential
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- DuplicateRecordFields
- ScopedTypeVariables
dependencies:
- protolude >=0.1.6 && <0.2
- attoparsec >=0.13.1.0 && <0.14
- base >=4.7 && <5
- text >=1.0 && <2.0
- time >=1.6 && <2.0
- pretty-show >=1.6 && <2.0
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Lib
  - Lib.Parser
  - Lib.FileReader
executables:
  sequential-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequential
tests:
  sequential-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequential
    - hspec >=2.4 && <3.0
